apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  namespace: {{.Values.namespace}}
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        ports:
        - containerPort: {{int .Values.containerPort}}
